### ISSUE TITLE
some message

### ISSUE THREAD

**Issue by iggimon** [daisy613/autoCoins#2]
while running this appears

Cannot index into a null array.
At C:\Users\Administrator\Desktop\WickHunter\autoCoins.ps1:87 char:9
+         $1hrPercentCurr = [math]::Abs((($1hrPrices[-1] - $1hrPrices[0 ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Users\Administrator\Desktop\WickHunter\autoCoins.ps1:91 char:9
+         $athPercentCurr = (($ath - $1hrPrices[-1]) * 100 / $ath)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
<img width="803" alt="Screenshot 2021-04-09 at 08 10 52" src="https://user-images.githubusercontent.com/18228252/114136650-93920b80-98fa-11eb-81f4-13904afcc7ca.png">

**Comment by daisy613** [comment]
Fixed in 1.1.0
