### ISSUE TITLE
max1hr24hrPercent

### ISSUE THREAD

**Issue by JohanSerf** [daisy613/autoCoins#4]
Hi, I'm not sure how this setting works.
I see the default value is 5, but what does it mean with 1hr/24h combination ?
Does it mean: Within the last 24 hours the price has moved 5% within any hour of the last 24 hours ?
or does it mean: Within the last 24 hours the price has moved 5% within the last hour of the last 24 hours ?
or does it mean: Within the last 24 hours the price has moved 5% ?
or does it mean: Within the last 1 hour the price has moved 5% ?

What value should I use for the following:
(Within the last 1 hour the price has moved 5%) OR (Within the last 24 hours the price has moved 20%)

I think it will be better to have two separate settings:
max1hrPercent and max24hrPercent

**Comment by tehzoca** [comment]
> What value should I use for the following:
> (Within the last 1 hour the price has moved 5%) OR (Within the last 24 hours the price has moved 20%)
> 
> I think it will be better to have two separate settings:
> max1hrPercent and max24hrPercent

exact the same as my thought
